{{- if not .Values.mssql.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mssql.fullname" . }}-secret
  labels:
    app: {{ template "mssql.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{ if .Values.mssql.saPassword }}
  {{ .Values.mssql.saPasswordKey }}: {{ .Values.mssql.saPassword | b64enc | quote }}
  {{ else }}
  {{ .Values.mssql.saPasswordKey }}: {{ randAlphaNum 20 | b64enc | quote }}
  {{ end }}
{{- end -}}
